### ISSUE TITLE
Activating/Deactivating Users

### ISSUE THREAD

**Issue by AndrewAlbizati** [ajockelle/CaseClaim#36]
The Users table has an `active` boolean value that doesn't change at the moment. Adding a developer-only command to deactivate and reactivate users would be beneficial so that users who aren't actively working at the helpdesk won't be able to interact with the core features of the bot.

Thinking longterm, this would help in preventing a hacked user from spamming claims, checking random cases, etc.

**Comment by ajockelle** [comment]
How is this different from giving / removing roles from users? 

When techs leave the HD the active roles, tech, lead, etc. are removed and they are given the Alumni tag.

Similarly upon joining, a user must be given rules such as tech, lead, etc. in order to interact with commands.

It should be noted that slash commands are not permitted to be used by users who do not have the Tech role.

**Comment by AndrewAlbizati** [comment]
That's a good point, I wasn't aware that alumni can't use slash commands.
