### ISSUE TITLE
Error when running claim command

### ISSUE THREAD

**Issue by ajockelle** [ajockelle/CaseClaim#69]
Error due to interaction not being responded to in time. 

Possible solution is to defer the interaction.

Additional investigation as to the cause of the slowdown is warranted to find if other commands may also need to be deferred.

**Comment by AndrewAlbizati** [comment]
After looking into it, the issue appears to be related to either hardware speed or ratelimiting (or a combination of the two). I looked into making the /claim command defer, however I don't think it would work in our situation.

When an interaction is deferred, it has to be specified whether or not it will be ephemeral. In our case, when the command is run we can't be sure if it'll be ephemeral or not because the parameters have to pass a few tests (make sure 2 people can't claim the same case).

For now, hopefully the issue is a oneoff.
