### ISSUE TITLE
/mycases emoji indicators

### ISSUE THREAD

**Issue by AndrewAlbizati** [ajockelle/CaseClaim#76]
Add emoji indicators for the status of a case in the `/mycases` command
- ✅ if checked
- 😁 if kudos
- 🛑 if pinged/resolved
- ✔️ if completed
- 🆗 if done

It would show up as:
- ✅ 12341234 `September 1st, 2023`
- ✅ 12341235 `September 1st, 2023`
- 🛑 12341236 `September 1st, 2023`
- 😁 12341237 `September 1st, 2023`

The purpose of this is to allow a tech to more easily see how they've been evaluated for a large group of cases at once. The emojis I've suggested will need to be changed, I just chose a few that I though worked fine.

Included in the embed would be a guide for how to interpret these emoji indicators.

**Comment by ajockelle** [comment]
We've determined that the percentage of cases checked in the case claim queue is sufficient information for a tech to generally understand how they are doing. 

At the moment, the statuses which are assigned to cases are more of an intermediary step taken by the auditing lead on shift. As such, they are not a processed form of feedback which we would like to pass on to the technician. Instead, these statuses are used by the QA leads who when writing evaluations in order to contextualize the cases they are reviewing.

While transparency is important, I feel that this level of transparency is redundant due to the fact that techs are aware of which cases are pinged (due to thread being created).

Ultimately, this command is meant for techs to easily access their most recent cases in case they must be revisited.

**Comment by AndrewAlbizati** [comment]
Ok, I can see how it's redundant.
